import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useApp } from '../src/context/AppContext';
import { Button } from '../src/components';
import { analytics } from '../src/services/analytics';
import { COLORS, SPACING, FONT_SIZES } from '../src/constants';

export default function MedicalDisclaimerScreen() {
  const router = useRouter();
  const { state, acknowledgeDisclaimer } = useApp();

  React.useEffect(() => {
    analytics.disclaimerShown();
  }, []);

  const handleAcknowledge = async () => {
    await acknowledgeDisclaimer();
    router.replace('/generating-plan');
  };

  const handleEditConditions = () => {
    router.push('/onboarding');
  };

  const medicalConditions = state.profile?.medical_conditions || [];

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView 
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
      >
        <View style={styles.header}>
          <View style={styles.iconContainer}>
            <Text style={styles.icon}>⚠️</Text>
          </View>
          <Text style={styles.title}>Medical Information Notice</Text>
        </View>

        <View style={styles.card}>
          <Text style={styles.cardTitle}>You've indicated:</Text>
          <View style={styles.conditionsList}>
            {medicalConditions.map((condition, index) => (
              <View key={index} style={styles.conditionItem}>
                <View style={styles.conditionDot} />
                <Text style={styles.conditionText}>
                  {condition.charAt(0).toUpperCase() + condition.slice(1)}
                </Text>
              </View>
            ))}
          </View>
        </View>

        <View style={styles.disclaimerBox}>
          <Text style={styles.disclaimerTitle}>Important Disclaimer</Text>
          <Text style={styles.disclaimerText}>
            This app does not provide medical advice. The meal plans and 
            recommendations are generated by AI based on general nutrition 
            guidelines and are not a substitute for professional medical advice, 
            diagnosis, or treatment.
          </Text>
          <Text style={styles.disclaimerText}>
            Please consult your doctor or a qualified healthcare provider before 
            following any meal plan, especially if you have the medical conditions 
            mentioned above.
          </Text>
        </View>

        <View style={styles.infoBox}>
          <Text style={styles.infoTitle}>What happens next?</Text>
          <View style={styles.infoItem}>
            <Text style={styles.infoBullet}>•</Text>
            <Text style={styles.infoText}>
              If you acknowledge this disclaimer, you'll receive a full 
              personalized plan
            </Text>
          </View>
          <View style={styles.infoItem}>
            <Text style={styles.infoBullet}>•</Text>
            <Text style={styles.infoText}>
              If you skip for now, you'll get a limited plan until you 
              acknowledge
            </Text>
          </View>
          <View style={styles.infoItem}>
            <Text style={styles.infoBullet}>•</Text>
            <Text style={styles.infoText}>
              This disclaimer will appear on your plan home as a reminder
            </Text>
          </View>
        </View>
      </ScrollView>

      <View style={styles.footer}>
        <Button
          title="I understand — continue"
          onPress={handleAcknowledge}
          size="large"
          style={styles.primaryButton}
        />
        <TouchableOpacity 
          style={styles.secondaryAction}
          onPress={handleEditConditions}
        >
          <Text style={styles.secondaryActionText}>
            Edit my medical conditions
          </Text>
        </TouchableOpacity>
        <TouchableOpacity 
          style={styles.skipAction}
          onPress={() => router.replace('/generating-plan')}
        >
          <Text style={styles.skipActionText}>
            Skip for now (limited plan)
          </Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: SPACING.lg,
    paddingBottom: SPACING.xxl,
  },
  header: {
    alignItems: 'center',
    marginBottom: SPACING.xl,
  },
  iconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: `${COLORS.warning}20`,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.md,
  },
  icon: {
    fontSize: 40,
  },
  title: {
    fontSize: FONT_SIZES.xl,
    fontWeight: '700',
    color: COLORS.text,
    textAlign: 'center',
  },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: SPACING.md,
    marginBottom: SPACING.md,
  },
  cardTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: SPACING.sm,
  },
  conditionsList: {},
  conditionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.xs,
  },
  conditionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.warning,
    marginRight: SPACING.sm,
  },
  conditionText: {
    fontSize: FONT_SIZES.md,
    color: COLORS.text,
  },
  disclaimerBox: {
    backgroundColor: `${COLORS.warning}15`,
    borderRadius: 16,
    padding: SPACING.md,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: `${COLORS.warning}40`,
  },
  disclaimerTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: SPACING.sm,
  },
  disclaimerText: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.text,
    lineHeight: 22,
    marginBottom: SPACING.sm,
  },
  infoBox: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: SPACING.md,
  },
  infoTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: SPACING.sm,
  },
  infoItem: {
    flexDirection: 'row',
    marginBottom: SPACING.sm,
  },
  infoBullet: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.primary,
    marginRight: SPACING.sm,
    fontWeight: '600',
  },
  infoText: {
    flex: 1,
    fontSize: FONT_SIZES.sm,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  footer: {
    padding: SPACING.lg,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.background,
  },
  primaryButton: {
    marginBottom: SPACING.md,
  },
  secondaryAction: {
    alignItems: 'center',
    paddingVertical: SPACING.sm,
    marginBottom: SPACING.xs,
  },
  secondaryActionText: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.primary,
    fontWeight: '500',
  },
  skipAction: {
    alignItems: 'center',
    paddingVertical: SPACING.sm,
  },
  skipActionText: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.textSecondary,
  },
});
